services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env 
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - grafana
    networks:
      - backend-network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # access Grafana in browser
    depends_on:
      - prometheus
    networks:
      - backend-network
    volumes:
      - grafana-data:/var/lib/grafana  # persistence

volumes:
  prometheus-data:
  grafana-data:

networks:
  backend-network:
    driver: bridge